### ISSUE TITLE
User can search and filter products 

### ISSUE THREAD

**Issue by jwld** [FACN1/Nasijona#16]
#38
- [x] Add search bar to landing page (#64)
- [ ] Add filter options to search results (#65)
- [ ] Create DB request for products (#66)
- [ ] Render results to page (#67)

**As a user**

> I want to be able to search and filter products

> So that I can see only those that I am interested in
