### ISSUE TITLE
User can post a Nazarene product on the app

### ISSUE THREAD

**Issue by jwld** [FACN1/Nasijona#2]
**Core**
- [x] User can create a profile page (#6)
- [x] User can post a new product (#8)

**Stretch Goals**
- [ ] User can update their profile (#7)
- [ ] User receives confirmation after posting a new product (#9)
- [ ] User can see the number of views on each product (#10)
- [ ] Seller can provide a way for the customer to contact them (#11)
