### ISSUE TITLE
User can register to NazBay

### ISSUE THREAD

**Issue by jwld** [FACN1/Nasijona#3]
#57

**As a user**
> I want to register on NazBay

> So that I can sell my product online

- [x] Create and style register page (#43)
- [x] Create and style register form (#44)
- [ ] Set up Facebook authentication (#45)
- [x] Submit information to DB (#68)
- [x] Add client-side validation (#74)
- [x] Hash user's password (#75)
