### ISSUE TITLE
User can purchase a Nazarene product on the app

### ISSUE THREAD

**Issue by jwld** [FACN1/Nasijona#38]
- [ ] User can search and filter products (#16)
- [ ] User can view a seller's profile page (#17)
- [ ] User can add a product to a shopping cart (#62)
- [ ] User can proceed to checkout screen and purchase a product (#40)
- [ ] User receives confirmation after purchasing a product (#41)
