### ISSUE TITLE
User can log in to their account on NazBay

### ISSUE THREAD

**Issue by jwld** [FACN1/Nasijona#4]
#57

**As a user**
> I want to login to my NazBay account

> So that I can interact with the platform

- [x] Create and style login page and form (#46)
- [ ] Add buttons for login through Facebook etc. (#47)
- [x] Remember user is logged in using JWTs (#48)
- [x] User can log in or log out from home page (#77)

**Comment by JWLD** [comment]
references #3
