### ISSUE TITLE
User can easily navigate the app

### ISSUE THREAD

**Issue by jwld** [FACN1/Nasijona#57]
- [x] User arrives on a friendly landing page (#18)
- [x] User can navigate between pages using a nav bar (#58)
- [x] User can register to NazBay (#3)
- [ ] User can login to NazBay (#4)
