### ISSUE TITLE
User can post a new product

### ISSUE THREAD

**Issue by jwld** [FACN1/Nasijona#8]
#2

**As a user**
> I want to be able to post a new product

> So that I can sell products on the website

- [x] Create and style new product page (#52)
- [x] Add form to new product page (#53)
- [x] Handle image upload to S3 (#51)
- [x] Create DB query to save product info (#70)
- [x] Redirect to new product on form submission (#54)

**Comment by JWLD** [comment]
this issue needs to be broken down to smaller user stories
